# Generated by Django 3.2.7 on 2021-09-09 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('minimum', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('amount_per_package', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('max_availability', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
