# Generated by Django 3.2.7 on 2021-09-10 10:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_order', '0002_itemsinorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsinorder',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
