# Generated by Django 3.2.7 on 2021-09-10 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buy_order', '0003_alter_itemsinorder_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsinorder',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='buy_order.buyorder'),
            preserve_default=False,
        ),
    ]
