# Generated by Django 3.2.7 on 2021-09-09 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('shopping_cart', '0002_productsincart'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsincart',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productsincart',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_in_cart', to='shopping_cart.shoppingcart'),
        ),
        migrations.AlterField(
            model_name='productsincart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_in_cart', to='products.product'),
        ),
    ]
